CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(13) NOT NULL,
  senha VARCHAR(128) NOT NULL,
  funcao VARCHAR(100) NOT NULL,
  foto VARCHAR(512) NOT NULL,
  criado_em TIMESTAMP NOT NULL,
  atualizado_em TIMESTAMP,
  token_resetar_senha VARCHAR(512)
);

ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);
ALTER TABLE usuario ADD CONSTRAINT ck_usuario_funcao CHECK (funcao IN ('USER', 'ADMIN'));
